### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by amilajack** [aularon/node-octopus#1]
@aularon just wondering if this project is still active

**Comment by aularon** [comment]
Unfortunately no.

**Comment by amilajack** [comment]
I was wondering if you could unpublish the module so that I can use the name 'octopus' for a project that I am working on.

**Comment by aularon** [comment]
Sure. The process goes, as I remember, by adding you as a publisher then removing myself, so you can publish your work. I will search some docs and then get back to you on this.

**Comment by aularon** [comment]
Please give me your npm username so I [can add you as a publisher](https://docs.npmjs.com/misc/disputes).

P.S. Please add a note to the README of the project linking this repo for some time, in case somebody was using it.

**Comment by amilajack** [comment]
My username is [amilajack](https://www.npmjs.com/~amilajack).

And by 'project linking this repo', do you mean this repo or my repo?

**Comment by aularon** [comment]
I mean [this repo](https://github.com/aularon/node-octopus): Linking the old project on the new project since it will take the shared name on npm registry.

**Comment by amilajack** [comment]
Got it! So should I make a PR to add a note to the readme saying:

"This repo has been deprecated. The npm package 'octopus' is now being used by another projecct"

Is this fine?

**Comment by aularon** [comment]
No! Sorry if I am not clear: Add a note to the README of [amilajack/octopus](https://github.com/amilajack/octopus), something like:

> ## Package naming
> 
> The name `octopus` on npm registry was used once by another project (web scraping framework). The old project lives [here](https://github.com/aularon/node-octopus).

Feel free to phrase it as you wish.

**Comment by amilajack** [comment]
Oh I see! Sorry for misunderstanding. I will add this.

**Comment by aularon** [comment]
(The repo is not deprecated, it is just not active enough so it justifies keeping the name, that's it. Wish you the best with your package).

**Comment by aularon** [comment]
I will add you as an owner as soon as I get to my workstation, and will let you know once I do.

**Comment by amilajack** [comment]
Just added the note to the [readme](https://github.com/amilajack/octopus/blob/master/readme.md)

**Comment by amilajack** [comment]
And thanks!

**Comment by aularon** [comment]
I just added you as an owner to penguin, you can continue from here.
You are welcome, my friend : )

**Comment by amilajack** [comment]
If I am not mistaken, I think you made me the admin of the wrong npm package. I was supposed to be made the admin of the `octopus` package. Is this okay?

**Comment by aularon** [comment]
Sorry, my bad!
I just fixed it, you are an owner of `octopus` now.
